/* AUTO-GENERATED by scripts/generate.mjs — do not edit by hand */
/* Source of truth: brand/tokens/*.json */

const preset = {
  "theme": {
    "extend": {
      "fontFamily": {
        "sans": [
          "var(--easyp-font-sans)",
          "sans-serif"
        ],
        "mono": [
          "var(--easyp-font-mono)",
          "monospace"
        ]
      },
      "fontSize": {
        "xs": "var(--easyp-size-xs)",
        "sm": "var(--easyp-size-sm)",
        "base": "var(--easyp-size-base)",
        "lg": "var(--easyp-size-lg)",
        "xl": "var(--easyp-size-xl)",
        "2xl": "var(--easyp-size-2xl)",
        "3xl": "var(--easyp-size-3xl)",
        "4xl": "var(--easyp-size-4xl)"
      },
      "colors": {
        "background": "var(--easyp-semantic-bg)",
        "foreground": "var(--easyp-semantic-fg)",
        "surface": "var(--easyp-semantic-surface, var(--easyp-color-slate-900))",
        "surfaceHighlight": "var(--easyp-color-slate-800)",
        "border": "var(--easyp-semantic-border)",
        "primary": "var(--easyp-semantic-primary)",
        "primaryGlow": "var(--easyp-semantic-primary-muted, var(--easyp-color-blue-400))",
        "secondary": "var(--easyp-semantic-secondary, var(--easyp-color-violet-500))",
        "accent": "var(--easyp-semantic-accent, var(--easyp-color-emerald-500))",
        "easyp": {
          "blue": {
            "400": "var(--easyp-color-blue-400)",
            "500": "var(--easyp-color-blue-500)",
            "600": "var(--easyp-color-blue-600)"
          },
          "violet": {
            "400": "var(--easyp-color-violet-400)",
            "500": "var(--easyp-color-violet-500)",
            "600": "var(--easyp-color-violet-600)"
          },
          "emerald": {
            "300": "var(--easyp-color-emerald-300)",
            "400": "var(--easyp-color-emerald-400)",
            "500": "var(--easyp-color-emerald-500)",
            "600": "var(--easyp-color-emerald-600)"
          },
          "red": {
            "400": "var(--easyp-color-red-400)",
            "500": "var(--easyp-color-red-500)"
          },
          "amber": {
            "400": "var(--easyp-color-amber-400)",
            "500": "var(--easyp-color-amber-500)"
          },
          "white": "var(--easyp-color-white)",
          "slate": {
            "50": "var(--easyp-color-slate-50)",
            "100": "var(--easyp-color-slate-100)",
            "200": "var(--easyp-color-slate-200)",
            "300": "var(--easyp-color-slate-300)",
            "400": "var(--easyp-color-slate-400)",
            "500": "var(--easyp-color-slate-500)",
            "600": "var(--easyp-color-slate-600)",
            "700": "var(--easyp-color-slate-700)",
            "800": "var(--easyp-color-slate-800)",
            "900": "var(--easyp-color-slate-900)",
            "950": "var(--easyp-color-slate-950)"
          }
        }
      },
      "borderRadius": {
        "easyp-sm": "var(--easyp-radius-sm)",
        "easyp-md": "var(--easyp-radius-md)",
        "easyp-lg": "var(--easyp-radius-lg)"
      },
      "boxShadow": {
        "easyp-sm": "var(--easyp-shadow-sm)",
        "easyp-md": "var(--easyp-shadow-md)",
        "easyp-lg": "var(--easyp-shadow-lg)"
      },
      "spacing": {
        "easyp-1": "var(--easyp-space-1)",
        "easyp-2": "var(--easyp-space-2)",
        "easyp-3": "var(--easyp-space-3)",
        "easyp-4": "var(--easyp-space-4)",
        "easyp-5": "var(--easyp-space-5)",
        "easyp-6": "var(--easyp-space-6)",
        "easyp-8": "var(--easyp-space-8)",
        "easyp-10": "var(--easyp-space-10)",
        "easyp-12": "var(--easyp-space-12)"
      }
    }
  }
};

export default preset;
