/**
 * Single source of truth: brand/tokens/*.json
 * Generates:
 *   - css/variables.css
 *   - tailwind/preset.js (ESM)
 *
 * Run: npm run generate  (also runs on npm prepare)
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const TOKENS = path.join(ROOT, 'tokens')

function loadJson(name) {
  return JSON.parse(fs.readFileSync(path.join(TOKENS, name), 'utf8'))
}

const colors = loadJson('colors.json')
const typography = loadJson('typography.json')
const radii = loadJson('radii.json')
const shadows = loadJson('shadows.json')
const spacing = loadJson('spacing.json')
const semantic = loadJson('semantic.json')

/** Resolve "{slate.500}" / "{white}" or raw value against colors */
function resolveColorRef(value) {
  if (typeof value !== 'string') return value
  const nested = value.match(/^\{([a-zA-Z0-9]+)\.([a-zA-Z0-9]+)\}$/)
  if (nested) {
    const [, group, key] = nested
    const g = colors[group]
    if (g == null) throw new Error(`Unknown color group: ${group} in ${value}`)
    if (typeof g === 'string') return g
    if (g[key] == null) throw new Error(`Unknown color: ${value}`)
    return g[key]
  }
  const top = value.match(/^\{([a-zA-Z0-9]+)\}$/)
  if (top) {
    const g = colors[top[1]]
    if (typeof g === 'string') return g
    throw new Error(`Unknown top-level color: ${value}`)
  }
  return value
}

function flattenColorVars(obj, prefix = []) {
  const lines = []
  for (const [key, val] of Object.entries(obj)) {
    if (typeof val === 'string') {
      const name = [...prefix, key].join('-')
      lines.push(`  --easyp-color-${name}: ${val};`)
    } else if (val && typeof val === 'object') {
      lines.push(...flattenColorVars(val, [...prefix, key]))
    }
  }
  return lines
}

/** @param {string} prefix e.g. marketing | semantic */
function semanticBlock(label, prefix, map) {
  const lines = [`  /* ${label} */`]
  for (const [key, raw] of Object.entries(map)) {
    const value = resolveColorRef(raw)
    const cssKey = key.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)
    lines.push(`  --easyp-${prefix}-${cssKey}: ${value};`)
  }
  return lines
}

function generateCss() {
  const lines = [
    '/* AUTO-GENERATED by scripts/generate.mjs — do not edit by hand */',
    '/* Source of truth: brand/tokens/*.json */',
    '',
    ':root {',
    '  /* palette */',
    ...flattenColorVars(colors),
    '',
    '  /* typography */',
    `  --easyp-font-sans: ${typography.fonts.sans};`,
    `  --easyp-font-mono: ${typography.fonts.mono};`,
    ...Object.entries(typography.sizes).map(
      ([k, v]) => `  --easyp-size-${k}: ${v};`,
    ),
    '',
    '  /* radii */',
    ...Object.entries(radii).map(([k, v]) => `  --easyp-radius-${k}: ${v};`),
    '',
    '  /* shadows */',
    ...Object.entries(shadows).map(([k, v]) => `  --easyp-shadow-${k}: ${v};`),
    '',
    '  /* spacing */',
    ...Object.entries(spacing).map(([k, v]) => `  --easyp-space-${k}: ${v};`),
    '',
    // Marketing (easyp.tech / docs): blue product accent — always available
    ...semanticBlock('marketing / docs (easyp.tech)', 'marketing', semantic.marketing),
    '',
    // Portal light defaults on :root for app without .dark
    ...semanticBlock('portal light (app.*)', 'semantic', semantic.light),
    '}',
    '',
    '.dark, [data-theme="dark"] {',
    ...semanticBlock('portal dark (app.*)', 'semantic', semantic.dark),
    '}',
    '',
    '/* Docs/marketing site: opt into product chrome via data attribute or class */',
    'html[data-brand="marketing"], .brand-marketing {',
    ...semanticBlock('marketing overrides as semantic for Tailwind primary/bg', 'semantic', {
      bg: semantic.marketing.bg,
      fg: semantic.marketing.fg,
      primary: semantic.marketing.primary,
      primaryMuted: semantic.marketing.primaryMuted,
      secondary: semantic.marketing.secondary,
      secondaryMuted: semantic.marketing.secondaryMuted,
      border: semantic.marketing.border,
      surface: semantic.marketing.surface,
    }),
    '}',
    '',
  ]
  return lines.join('\n')
}

function generatePreset() {
  const easypColors = {}
  for (const [name, scale] of Object.entries(colors)) {
    if (typeof scale === 'string') {
      easypColors[name] = `var(--easyp-color-${name})`
    } else {
      easypColors[name] = {}
      for (const step of Object.keys(scale)) {
        easypColors[name][step] = `var(--easyp-color-${name}-${step})`
      }
    }
  }

  const fontSize = {}
  for (const k of Object.keys(typography.sizes)) {
    fontSize[k] = `var(--easyp-size-${k})`
  }

  const preset = {
    theme: {
      extend: {
        fontFamily: {
          sans: ['var(--easyp-font-sans)', 'sans-serif'],
          mono: ['var(--easyp-font-mono)', 'monospace'],
        },
        fontSize,
        colors: {
          // Use --easyp-semantic-* so marketing html sets product blue, portal sets slate/emerald
          background: 'var(--easyp-semantic-bg)',
          foreground: 'var(--easyp-semantic-fg)',
          surface: 'var(--easyp-semantic-surface, var(--easyp-color-slate-900))',
          surfaceHighlight: 'var(--easyp-color-slate-800)',
          border: 'var(--easyp-semantic-border)',
          primary: 'var(--easyp-semantic-primary)',
          primaryGlow: 'var(--easyp-semantic-primary-muted, var(--easyp-color-blue-400))',
          secondary: 'var(--easyp-semantic-secondary, var(--easyp-color-violet-500))',
          accent: 'var(--easyp-semantic-accent, var(--easyp-color-emerald-500))',
          easyp: easypColors,
        },
        borderRadius: {
          'easyp-sm': 'var(--easyp-radius-sm)',
          'easyp-md': 'var(--easyp-radius-md)',
          'easyp-lg': 'var(--easyp-radius-lg)',
        },
        boxShadow: {
          'easyp-sm': 'var(--easyp-shadow-sm)',
          'easyp-md': 'var(--easyp-shadow-md)',
          'easyp-lg': 'var(--easyp-shadow-lg)',
        },
        spacing: Object.fromEntries(
          Object.keys(spacing).map((k) => [`easyp-${k}`, `var(--easyp-space-${k})`]),
        ),
      },
    },
  }

  return [
    '/* AUTO-GENERATED by scripts/generate.mjs — do not edit by hand */',
    '/* Source of truth: brand/tokens/*.json */',
    '',
    `const preset = ${JSON.stringify(preset, null, 2)};`,
    '',
    'export default preset;',
    '',
  ].join('\n')
}

function main() {
  const cssPath = path.join(ROOT, 'css', 'variables.css')
  const presetPath = path.join(ROOT, 'tailwind', 'preset.js')
  fs.mkdirSync(path.dirname(cssPath), { recursive: true })
  fs.mkdirSync(path.dirname(presetPath), { recursive: true })
  fs.writeFileSync(cssPath, generateCss())
  fs.writeFileSync(presetPath, generatePreset())
  console.log('Generated:', path.relative(ROOT, cssPath))
  console.log('Generated:', path.relative(ROOT, presetPath))
}

main()
